### ISSUE TITLE
discuss initial release

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/MTP40F#2]

**Comment by RobTillaart** [comment]
TODO readme .md 
- warning section should not be in interface (done)
- reorder the interface section

- add schema to examples  (done)
```
              UNO                     MTP40F
        +---------------+        +---------------+
        |               |        |               |
        |          +5V  |--------| 1 VIN         |
        |          GND  |--------| 2 GND         |
        |               |        | 3             |
        |               |        | 4             |
        |               |        |               |
        |               |        | 5             |
        |         RX 6  |--------| 6 TX          |
        |         TX 7  |--------| 7 RX          |
        |               |        | 8             |
        |               |        | 9             |
        |               |        |               |
        +---------------+        +---------------+

  use SoftwareSerial sws(7,6);
```

**Comment by M66B** [comment]
I tried something similar with a Wemos D1 mini version 4, but there was never a response from the sensor. Maybe the signal voltage levels are different?

**Comment by RobTillaart** [comment]
> I tried something similar with a Wemos D1 mini version 4, but there was never a response from the sensor. Maybe the signal voltage levels are different?

I do not have a Wemos to confirm, but the sensor definitely needs +5V to power up. 
You might add 10K pull ups on the TX and RX line.

**Comment by RobTillaart** [comment]
test with ESP32 - hardware Serial1 - works. This is a 3V3 device.

```
5000	2
10000	2
15000	977
20000	1272
25000	1375
30000	1384
35000	1379
40000	1371
45000	1340
50000	1336

TIME	CO2 LEVEL
55000	1328
60000	1321
65000	990
```

Do you have a link to a pin map of the Wemos used?

**Comment by M66B** [comment]
If you are looking for pin number mapping Wemos/Arduino:

https://chewett.co.uk/blog/1066/pin-numbering-for-wemos-d1-mini-esp8266/

I've tried two pairs of pins with software serial.

**Comment by RobTillaart** [comment]
What I often have with serial is that I need to swap TX and RX. Swapped maybe 25 times before I got first light with this sensor :)

![image](https://github.com/RobTillaart/MTP40F/assets/462844/7756f1ab-63f0-48e3-8b9f-1361fa18ab0f)

you could use pin 7 and 8 as hardware serial2 if I read this diagram correctly.

**Comment by RobTillaart** [comment]
@M66B 
updated the library to 0.1.1
Most important is a bugfix when the status bit indicate invalid data . 
Not seen in real life yet but should be handled correctly.

**Comment by M66B** [comment]
@RobTillaart I've received an MH-Z19B yesterday, which I will be using. Let's see if that works with a Wemos D1 mini.

**Comment by M66B** [comment]
I had the same problem with the MZ-19B, but I've resolved it. Not all I/O pins are equal:

https://github.com/Erriez/ErriezMHZ19B#pins

Using pin D5 and D6 works!

I'll later test with the MTP40F too, and let you know the results.

**Comment by M66B** [comment]
It works with the MTP40F too!
I'll test a bit more tomorrow, but reading the gas concentration is okay.

**Comment by RobTillaart** [comment]
Si just a different set op pins solved it.
Learned something (again) today

**Comment by RobTillaart** [comment]
@M66B 
Found this issue still open after 3 weeks silence. The 0.1.1 version solved most important problems.
So I will close this one.

If there are other things that need to be solved in the library, please create a new issue.
